on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Website via SCP and SSH
      run: |
        # Copy files to the server (adjust /var/www/html/ to your path)
        scp -r ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/website/

        # SSH into server and move files
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo mkdir -p /var/www/html/
          sudo cp -r /tmp/website/* /var/www/html/
          sudo systemctl restart nginx || sudo systemctl restart httpd
        EOF
